### PR TITLE
feat(verticals): implement vertical lookups

### PR DESCRIPTION
**Pull request by keremciu**
- Implements vertical lookups to consume in website project to build product grid and later on use it for other apps

Vertical lookup, includes images and texts related to that insurance product

### CODE REVIEW

**Comment by kimkwanka** [comment]
Is this going to be used in app (RectTool) as well?

**Comment by keremciu** [comment]
> Is this going to be used in app (RecTool) as well?

yep but it will happen in a later point as we have to discuss with design how to make them a bit similar (like naming of vertical groups etc) but I wanted to follow an extendable approach. let me know if you have any improvement idea, I was thinking using enums to extend easily later but I believe for now it's okay to make everything for website

**Comment by kimkwanka** [comment]
> > Is this going to be used in app (RecTool) as well?
> 
> yep but it will happen in a later point as we have to discuss with design how to make them a bit similar (like naming of vertical groups etc) but I wanted to follow an extendable approach. let me know if you have any improvement idea, I was thinking using enums to extend easily later but I believe for now it's okay to make everything just for website

I was asking since it would then be helpful to somehow include the translation strings (for app). But I'm not quite sure what the best approach for something like that would be :/

**Review by kimkwanka — APPROVED** [review]

**Review by talo242 — COMMENTED** [review]
🙌🏼

**Pull request merged**
